matrix:
  include:
    - language: android
      dist: trusty
      cache: npm
      android:
        components:
          # use the latest revision of Android SDK Tools
          - tools
          - platform-tools

          # The BuildTools version used by your project
          - build-tools-28.0.3

          # The SDK version used to compile your project
          - android-28

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      before_install:
        - cd template
      install:
        - nvm install 12.14.0
        - npm i
      before_script:
        - cd android
      script:
        - ./gradlew assembleRelease

    - language: objective-c
      os: osx
      osx_image: xcode11.3
      podfile: template/ios/Podfile
      cache:
        - cocoapods
        - npm
      before_install:
        - cd template
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - gem install cocoapods
        - nvm install 12.14.0
        - npm i
      before_script:
        - cd ios
        - pod install
        - cd ..
      script:
        - npm run detox:b:ios:r | xcpretty
        - npm run detox:t:ios:r --cleanup
